name: Build scrcpy-mobile iOS
on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # 【新增的破局神抽】：强制降级并锁定 CMake 到 3.x 时代，完美兼容老代码
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.6'

      - name: Install dependencies
        run: |
          # 1. 基础依赖中追加 fmt 和 pkg-config，消灭找不到包的错误
          brew install ffmpeg sdl2 golang fmt pkg-config
          
          # 2. 从 Google 下载特定的 protoc 28.3
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-osx-aarch_64.zip
          unzip protoc-28.3-osx-aarch_64.zip -d $HOME/protoc_env
          
          # 3. 注入环境变量
          export PATH="$HOME/protoc_env/bin:$PATH"
          echo "$HOME/protoc_env/bin" >> $GITHUB_PATH
          protoc --version
          
          # 4. 再次向胜利冲锋
          make libs
          make -C porting scrcpy-server

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -project scrcpy-ios/scrcpy-ios.xcodeproj \
            -scheme "scrcpy-ios" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package to IPA
        run: |
          mkdir -p Payload
          mv scrcpy-ios/build/Release-iphoneos/scrcpy-ios.app Payload/
          zip -r scrcpy-mobile.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: scrcpy-mobile-ipa
          path: scrcpy-mobile.ipa
